"""Configuration file for nmea-mqtt-py

    DO NOT EDIT THIS FILE!

Instead, copy it to config.py, then edit the copy.
     cp config-sample.py config.py
     nano config.py
"""

# Set to 1 for debug messages
DEBUG = 0

# Settings related to the NMEA socket connection
NMEA_HOST = "localhost"
NMEA_PORT = 10110
NMEA_TIMEOUT = 20
NMEA_RETRY_WAIT = 60

# How often, in seconds, to write a depth record to the CSV file
WRITE_INTERVAL = 10
# How old, in seconds, a position report can be and still be useful
MAX_STALE = 60

# Where to write
CSV_FILE = "/var/tmp/depth.csv"
